name: Generate Contribution Snake Animation

on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # This is crucial for pushing changes
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true  # This keeps the auth token for later pushes

      - name: Generate Snake Animation
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            assets/github-contribution-snake.svg
            assets/github-contribution-snake-dark.svg?palette=github-dark

      - name: Commit and Push Changes
        run: |
          git config --global user.name "xingstar"
          git config --global user.email "2115438238@qq.com"
          git add assets/
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit"
          else
            git commit -m "Update contribution snake animation [skip ci]"
            git push
          fi
