name: Generate Contribution Snake Animation

on:
  # Run daily at 2 AM UTC
  schedule:
    - cron: "0 2 * * *"
  
  # Allow manual triggering
  workflow_dispatch:
  
  # Run on pushes to main branch
  push:
    branches:
      - main

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    timeout-minutes: 15  # Increased timeout for reliability
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Generate Snake Animation
        uses: Platane/snk/svg-only@v3
        id: generate-snake
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            assets/github-contribution-snake.svg
            assets/github-contribution-snake-dark.svg?palette=github-dark
          
      - name: Commit and Push Results
        run: |
          git config --global user.name "xingstar"
          git config --global user.email "2115438238@qq.com"
          git add assets/
          git commit -m "Update contribution snake animation [skip ci]"
          git push
