name: Generate Contribution Snake Animation

on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}  # Add this line
          persist-credentials: true  # Add this line
        
      - name: Generate Snake Animation
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            assets/github-contribution-snake.svg
            assets/github-contribution-snake-dark.svg?palette=github-dark
          
      - name: Commit and Push Results
        run: |
          git config --global user.name "xingstar"
          git config --global user.email "2115438238@qq.com"
          git add assets/
          git commit -m "Update contribution snake animation [skip ci]"
          git push
